<a href="https://colab.research.google.com/github/SHAIKMEHANAZ/Development-of-Healthcare-Operations-Intelligence-Dashboard-with-Decision-Analytics/blob/main/SQL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import sqlite3

conn = sqlite3.connect("employee.db")
cursor = conn.cursor()

# Add DROP TABLE IF EXISTS to ensure a clean slate if the table already exists
cursor.execute("DROP TABLE IF EXISTS Employee;")

cursor.execute("""
CREATE TABLE Employee (
    Emp_ID INTEGER PRIMARY KEY,
    Emp_Name TEXT,
    Department TEXT,
    Job_Role TEXT,
    Salary REAL,
    Age INTEGER,
    City TEXT,
    Experience INTEGER
)
""")

conn.commit()
print("Table 'Employee' created successfully.")

Table 'Employee' created successfully.

In [7]:
# Insert Employee Values
# Delete existing data to prevent UNIQUE constraint violation on re-execution
cursor.execute("DELETE FROM Employee;")

insert_data_sql = """
INSERT INTO Employee
(Emp_ID, Emp_Name, Department, Job_Role, Salary, Age, City, Experience)
VALUES
(101, 'Rahul', 'IT', 'Developer', 55000, 25, 'Hyderabad', 2),
(102, 'Priya', 'HR', 'HR Executive', 45000, 28, 'Chennai', 4),
(103, 'Arun', 'IT', 'Tester', 48000, 24, 'Bangalore', 2),
(104, 'Sneha', 'Finance', 'Accountant', 52000, 30, 'Hyderabad', 6),
(105, 'Kiran', 'IT', 'Developer', 65000, 32, 'Chennai', 8),
(106, 'Anjali', 'Sales', 'Sales Executive', 42000, 26, 'Bangalore', 3),
(107, 'Vijay', 'Finance', 'Manager', 75000, 38, 'Hyderabad', 12),
(108, 'Meena', 'HR', 'Recruiter', 40000, 27, 'Bangalore', 3),
(109, 'Suresh', 'Sales', 'Sales Manager', 68000, 35, 'Chennai', 10),
(110, 'Divya', 'IT', 'Data Analyst', 60000, 29, 'Hyderabad', 5);
"""
cursor.execute(insert_data_sql)
conn.commit()
print("Sample data inserted into 'Employee' table successfully.")

Sample data inserted into 'Employee' table successfully.

In [41]:
#1. SELECT — Display all employees
import sqlite3
import pandas as pd

conn = sqlite3.connect("employee.db")
cursor = conn.cursor()

df = pd.read_sql_query("SELECT * FROM Employee", conn)

display(df)

,Emp_ID,Emp_Name,Department,Job_Role,Salary,Age,City,Experience
0,101,Rahul,IT,Developer,55000.0,25,Hyderabad,2
1,102,Priya,HR,HR Executive,45000.0,28,Chennai,4
2,103,Arun,IT,Tester,48000.0,24,Bangalore,2
3,104,Sneha,Finance,Accountant,52000.0,30,Hyderabad,6
4,105,Kiran,IT,Developer,65000.0,32,Chennai,8
5,106,Anjali,Sales,Sales Executive,42000.0,26,Bangalore,3
6,107,Vijay,Finance,Manager,75000.0,38,Hyderabad,12
7,108,Meena,HR,Recruiter,40000.0,27,Bangalore,3
8,109,Suresh,Sales,Sales Manager,68000.0,35,Chennai,10
9,110,Divya,IT,Data Analyst,60000.0,29,Hyderabad,5

In [42]:
#2. WHERE — Employees from IT
df = pd.read_sql_query("""
SELECT *
FROM Employee
WHERE Department = 'IT';
""", conn)

display(df)

,Emp_ID,Emp_Name,Department,Job_Role,Salary,Age,City,Experience
0,101,Rahul,IT,Developer,55000.0,25,Hyderabad,2
1,103,Arun,IT,Tester,48000.0,24,Bangalore,2
2,105,Kiran,IT,Developer,65000.0,32,Chennai,8
3,110,Divya,IT,Data Analyst,60000.0,29,Hyderabad,5

In [43]:
#3. Conditions — Salary greater than 50,000
df = pd.read_sql_query("""
SELECT Emp_Name, Salary
FROM Employee
WHERE Salary > 50000;
""", conn)

display(df)

  Emp_Name   Salary
0    Rahul  55000.0
1    Sneha  52000.0
2    Kiran  65000.0
3    Vijay  75000.0
4   Suresh  68000.0
5    Divya  60000.0

In [44]:
#4. AND — IT employees with salary above 50,000
df = pd.read_sql_query("""
SELECT Emp_Name, Department, Salary
FROM Employee
WHERE Department = 'IT'
AND Salary > 50000;
""", conn)

display(df)

  Emp_Name Department   Salary
0    Rahul         IT  55000.0
1    Kiran         IT  65000.0
2    Divya         IT  60000.0

In [45]:
#5. LIKE — Names starting with S
df = pd.read_sql_query("""
SELECT *
FROM Employee
WHERE Emp_Name LIKE 'S%';
""", conn)

display(df)

,Emp_ID,Emp_Name,Department,Job_Role,Salary,Age,City,Experience
0,104,Sneha,Finance,Accountant,52000.0,30,Hyderabad,6
1,109,Suresh,Sales,Sales Manager,68000.0,35,Chennai,10

In [46]:
#6. Aggregate Functions — Salary calculation
df = pd.read_sql_query("""
SELECT
    COUNT(*) AS Total_Employees,
    SUM(Salary) AS Total_Salary,
    AVG(Salary) AS Average_Salary,
    MAX(Salary) AS Maximum_Salary,
    MIN(Salary) AS Minimum_Salary
FROM Employee;
""", conn)

display(df)

,Total_Employees,Total_Salary,Average_Salary,Maximum_Salary,Minimum_Salary
0,10,550000.0,55000.0,75000.0,40000.0

In [47]:
#7. GROUP BY — Employees in each department
df = pd.read_sql_query("""
SELECT
    Department,
    COUNT(*) AS Employee_Count
FROM Employee
GROUP BY Department;
""", conn)

display(df)

  Department  Employee_Count
0    Finance               2
1         HR               2
2         IT               4
3      Sales               2

In [48]:
#8. HAVING — Departments with average salary above 50,000
df = pd.read_sql_query("""
SELECT
    Department,
    AVG(Salary) AS Average_Salary
FROM Employee
GROUP BY Department
HAVING AVG(Salary) > 50000;
""", conn)

display(df)

  Department  Average_Salary
0    Finance         63500.0
1         IT         57000.0
2      Sales         55000.0

In [49]:
#9. IN — Employees from Hyderabad or Chennai
df = pd.read_sql_query("""
SELECT Emp_Name, City
FROM Employee
WHERE City IN ('Hyderabad', 'Chennai');
""", conn)

display(df)

  Emp_Name       City
0    Rahul  Hyderabad
1    Priya    Chennai
2    Sneha  Hyderabad
3    Kiran    Chennai
4    Vijay  Hyderabad
5   Suresh    Chennai
6    Divya  Hyderabad

In [50]:
#10. BETWEEN — Salary between 45,000 and 65,000
df = pd.read_sql_query("""
SELECT Emp_Name, Salary
FROM Employee
WHERE Salary BETWEEN 45000 AND 65000;
""", conn)

display(df)

  Emp_Name   Salary
0    Rahul  55000.0
1    Priya  45000.0
2     Arun  48000.0
3    Sneha  52000.0
4    Kiran  65000.0
5    Divya  60000.0